//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetClients.DemoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FleetClients.DemoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Fleet Manager Client Control
        ///
        ///A control used to display the current state of the AGV fleet.
        ///
        ///## Configuration
        ///
        ///Create a new fleet manager client:
        ///
        ///```csharp
        ///IFleetManagerClient client = FleetClients.ClientFactory.CreateTcpFleetManagerClient(new EndpointSettings(System.Net.IPAddress.Loopback));
        ///```
        ///
        ///and set the controls data context to it.
        ///
        ///## Components
        ///
        ///### Fleet Manager Client Control
        ///
        ///This displays all kingpins currenly present in the fleet. The kingpin state control from the nuget pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FleetManagerClientControlDescription {
            get {
                return ResourceManager.GetString("FleetManagerClientControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Fleet Template Control
        ///
        ///A control used to create and edit a fleet template. Represents a virtual vehicle fleet that can be created instantly, rather than manually creating and positioning virtual AGVs within the scheduler.
        ///
        ///The template can be imported from exported to json.
        ///.
        /// </summary>
        internal static string FleetTemplateControlDescription {
            get {
                return ResourceManager.GetString("FleetTemplateControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Fleet Clients Demo App
        ///
        ///Demonstrates the functionality available in the FleetClients and FleetClients.Controls assemblies.
        ///
        ///## Configuration
        ///
        ///Set the IP address of the scheduler to connect to in the configuration section.
        ///
        ///## Controls Library
        ///
        ///### Fleet Manager Client Control
        ///
        ///Creates a new window hosting the fleet manager client control, a control that is used to display the current state of the AGV free..
        /// </summary>
        internal static string MainWindowDescription {
            get {
                return ResourceManager.GetString("MainWindowDescription", resourceCulture);
            }
        }
    }
}
