//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetClients.FleetManagerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCallData", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    [System.SerializableAttribute()]
    public partial class ServiceCallData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FleetClients.FleetManagerServiceReference.ServiceCode ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetClients.FleetManagerServiceReference.ServiceCode ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((this.ServiceCodeField.Equals(value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCode", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    public enum ServiceCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICENOTCONFIGURED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENTEXCEPTION = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICEUNAVAILABLE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICENOTIMPLEMENTED = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INTERNALERROR = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETSEMVERFAILED = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMMITJOBFAILED = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATEJOBFAILED = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATEUNORDEREDLISTTASKFAILED = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATEATOMICMOVELISTTASKFAILED = 1004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATEORDEREDLISTTASKFAILED = 1005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATESERVICINGTASKFAILED = 1006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTACCEPTINGNEWJOBS = 1007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DIRECTIVENOTALLOWED = 1008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALIDNODETASKID = 1009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATESLEEPINGTASKFAILED = 1010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATEGOTONODETASKFAILED = 1011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATEATOMICMOVETASKFAILED = 1012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BEGINEDITINGJOBFAILED = 1013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINISHEDITINGJOBFAILED = 1014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BEGINEDITINGTASKFAILED = 1015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINISHEDITINGTASKFAILED = 1016,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATEAWAITINGTASKFAILED = 1017,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ABORTALLJOBSFAILED = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ABORTALLJOBSFORAGENTFAILED = 2002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ABORTJOBFAILED = 2003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETACTIVEJOBSFORAGENTFAILED = 2004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ABORTTASKFAILED = 2005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESOLVEFAULTEDJOBFAILED = 2006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESOLVEFAULTEDTASKFAILED = 2007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETJOBSTATEFAILED = 3001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALIDJOBID = 3002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALIDTASKID = 3003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETALLMOVEDATAFAILED = 4001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETALLNODEDATAFAILED = 4002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETMAPPINGKEYCARDSIGNATUREFAILED = 4003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETRAJECTORYFAILED = 4004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALIDMOVEID = 4005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SETOCCUPYINGMANDATEFAILED = 4006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLEAROCCUPYINGMANDATEFAILED = 4007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONTAINSINVALIDMAPITEMIDS = 4008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONTAINSINVALIDTIMEOUT = 4009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OCCUPATIONALREADYINPROGRESS = 4010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETOCCUPYINGMANDATEPROGRESSDATAFAILED = 4011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETOUTSTANDINGSERVICEREQUESTSFAILED = 5001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SETSERVICECOMPLETEFAILED = 5002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETALLAGENTDATAFAILED = 6001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETALLAGENTSINLIFETIMESTATEFAILED = 6002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SETAGENTLIFETIMESTATEFAILED = 6003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMMITINSTRUCTIONFAILED = 7001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUESTFREEZEFAILED = 7002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUESTUNFREEZEFAILED = 7003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INCORRECTNUMBEROFBYTES = 7004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMMITEXTENDEDWAYPOINTSFAILED = 7005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETKINGPINDESCRIPTIONFAILED = 7008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATEVIRTUALVEHICLEFAILED = 7009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REMOVEVEHICLEFAILED = 7010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SETPOSEFAILED = 7011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESETKINGPINFAILED = 7012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENABLEALLVEHICLESFAILED = 7013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISABLEALLVEHICLESFAILED = 7014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALIDIPADDRESS = 7015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENABLEVEHICLEFAILED = 7016,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISABLEVEHICLEFAILED = 7017,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SETFLEETSTATEFAILED = 7018,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SETKINGPINSTATEFAILED = 7019,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOWNLOADFAILED = 8001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPLOADFAILED = 8002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETFILENAMESFAILED = 8003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALIDAGENTID = 9001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALIDSTATECASTVARIABLEALIAS = 9002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STATECASTVARIABLEDATATYPEMISMATCH = 9003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETSCHEDULERVERSIONFAILED = 10001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETPLUGINVERSIONSFAILED = 10002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GETOUTSTANDINGAGENTREQUESTSFAILED = 11001,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PoseData", Namespace="http://schemas.datacontract.org/2004/07/Controllers.Vehicles.Fleet")]
    [System.SerializableAttribute()]
    public partial class PoseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeadingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Heading {
            get {
                return this.HeadingField;
            }
            set {
                if ((this.HeadingField.Equals(value) != true)) {
                    this.HeadingField = value;
                    this.RaisePropertyChanged("Heading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleControllerState", Namespace="http://schemas.datacontract.org/2004/07/Controllers.Vehicles")]
    public enum VehicleControllerState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetState", Namespace="http://schemas.datacontract.org/2004/07/Controllers.Vehicles.Fleet")]
    [System.SerializableAttribute()]
    public partial class FleetState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GACore.KingpinStateData[] KingpinStatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TickField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GACore.KingpinStateData[] KingpinStates {
            get {
                return this.KingpinStatesField;
            }
            set {
                if ((object.ReferenceEquals(this.KingpinStatesField, value) != true)) {
                    this.KingpinStatesField = value;
                    this.RaisePropertyChanged("KingpinStates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Tick {
            get {
                return this.TickField;
            }
            set {
                if ((this.TickField.Equals(value) != true)) {
                    this.TickField = value;
                    this.RaisePropertyChanged("Tick");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FleetManagerServiceReference.IFleetManagerService", CallbackContract=typeof(FleetClients.FleetManagerServiceReference.IFleetManagerServiceCallback))]
    public interface IFleetManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSemVer", ReplyAction="http://tempuri.org/IService/GetSemVerResponse")]
        System.Tuple<GACore.SemVerData, FleetClients.FleetManagerServiceReference.ServiceCallData> GetSemVer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSemVer", ReplyAction="http://tempuri.org/IService/GetSemVerResponse")]
        System.Threading.Tasks.Task<System.Tuple<GACore.SemVerData, FleetClients.FleetManagerServiceReference.ServiceCallData>> GetSemVerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriptionService/SubscriptionHeartbeat", ReplyAction="http://tempuri.org/ISubscriptionService/SubscriptionHeartbeatResponse")]
        void SubscriptionHeartbeat(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriptionService/SubscriptionHeartbeat", ReplyAction="http://tempuri.org/ISubscriptionService/SubscriptionHeartbeatResponse")]
        System.Threading.Tasks.Task SubscriptionHeartbeatAsync(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/GetKingpinDescription", ReplyAction="http://tempuri.org/IFleetManagerService/GetKingpinDescriptionResponse")]
        System.Tuple<System.Xml.Linq.XElement, FleetClients.FleetManagerServiceReference.ServiceCallData> GetKingpinDescription(System.Net.IPAddress ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/GetKingpinDescription", ReplyAction="http://tempuri.org/IFleetManagerService/GetKingpinDescriptionResponse")]
        System.Threading.Tasks.Task<System.Tuple<System.Xml.Linq.XElement, FleetClients.FleetManagerServiceReference.ServiceCallData>> GetKingpinDescriptionAsync(System.Net.IPAddress ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/CommitEx2Waypoints", ReplyAction="http://tempuri.org/IFleetManagerService/CommitEx2WaypointsResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> CommitEx2Waypoints(System.Net.IPAddress ipAddress, int instructionId, byte[] ex2WaypointBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/CommitEx2Waypoints", ReplyAction="http://tempuri.org/IFleetManagerService/CommitEx2WaypointsResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> CommitEx2WaypointsAsync(System.Net.IPAddress ipAddress, int instructionId, byte[] ex2WaypointBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/RequestFreeze", ReplyAction="http://tempuri.org/IFleetManagerService/RequestFreezeResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> RequestFreeze();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/RequestFreeze", ReplyAction="http://tempuri.org/IFleetManagerService/RequestFreezeResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> RequestFreezeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/RequestUnfreeze", ReplyAction="http://tempuri.org/IFleetManagerService/RequestUnfreezeResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> RequestUnfreeze();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/RequestUnfreeze", ReplyAction="http://tempuri.org/IFleetManagerService/RequestUnfreezeResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> RequestUnfreezeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/CreateVirtualVehicle", ReplyAction="http://tempuri.org/IFleetManagerService/CreateVirtualVehicleResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> CreateVirtualVehicle(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.PoseData pose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/CreateVirtualVehicle", ReplyAction="http://tempuri.org/IFleetManagerService/CreateVirtualVehicleResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> CreateVirtualVehicleAsync(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.PoseData pose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/RemoveVehicle", ReplyAction="http://tempuri.org/IFleetManagerService/RemoveVehicleResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> RemoveVehicle(System.Net.IPAddress ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/RemoveVehicle", ReplyAction="http://tempuri.org/IFleetManagerService/RemoveVehicleResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> RemoveVehicleAsync(System.Net.IPAddress ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/SetPose", ReplyAction="http://tempuri.org/IFleetManagerService/SetPoseResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> SetPose(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.PoseData pose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/SetPose", ReplyAction="http://tempuri.org/IFleetManagerService/SetPoseResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> SetPoseAsync(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.PoseData pose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/ResetKingpin", ReplyAction="http://tempuri.org/IFleetManagerService/ResetKingpinResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> ResetKingpin(System.Net.IPAddress ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/ResetKingpin", ReplyAction="http://tempuri.org/IFleetManagerService/ResetKingpinResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> ResetKingpinAsync(System.Net.IPAddress ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/SetFleetState", ReplyAction="http://tempuri.org/IFleetManagerService/SetFleetStateResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> SetFleetState(FleetClients.FleetManagerServiceReference.VehicleControllerState controllerState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/SetFleetState", ReplyAction="http://tempuri.org/IFleetManagerService/SetFleetStateResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> SetFleetStateAsync(FleetClients.FleetManagerServiceReference.VehicleControllerState controllerState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/SetKingpinState", ReplyAction="http://tempuri.org/IFleetManagerService/SetKingpinStateResponse")]
        System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> SetKingpinState(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.VehicleControllerState controllerState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/SetKingpinState", ReplyAction="http://tempuri.org/IFleetManagerService/SetKingpinStateResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> SetKingpinStateAsync(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.VehicleControllerState controllerState);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFleetManagerServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetManagerService/OnCallback", ReplyAction="http://tempuri.org/IFleetManagerService/OnCallbackResponse")]
        void OnCallback(FleetClients.FleetManagerServiceReference.FleetState callbackObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFleetManagerServiceChannel : FleetClients.FleetManagerServiceReference.IFleetManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FleetManagerServiceClient : System.ServiceModel.DuplexClientBase<FleetClients.FleetManagerServiceReference.IFleetManagerService>, FleetClients.FleetManagerServiceReference.IFleetManagerService {
        
        public FleetManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FleetManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FleetManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FleetManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FleetManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.Tuple<GACore.SemVerData, FleetClients.FleetManagerServiceReference.ServiceCallData> GetSemVer() {
            return base.Channel.GetSemVer();
        }
        
        public System.Threading.Tasks.Task<System.Tuple<GACore.SemVerData, FleetClients.FleetManagerServiceReference.ServiceCallData>> GetSemVerAsync() {
            return base.Channel.GetSemVerAsync();
        }
        
        public void SubscriptionHeartbeat(System.Guid guid) {
            base.Channel.SubscriptionHeartbeat(guid);
        }
        
        public System.Threading.Tasks.Task SubscriptionHeartbeatAsync(System.Guid guid) {
            return base.Channel.SubscriptionHeartbeatAsync(guid);
        }
        
        public System.Tuple<System.Xml.Linq.XElement, FleetClients.FleetManagerServiceReference.ServiceCallData> GetKingpinDescription(System.Net.IPAddress ipAddress) {
            return base.Channel.GetKingpinDescription(ipAddress);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<System.Xml.Linq.XElement, FleetClients.FleetManagerServiceReference.ServiceCallData>> GetKingpinDescriptionAsync(System.Net.IPAddress ipAddress) {
            return base.Channel.GetKingpinDescriptionAsync(ipAddress);
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> CommitEx2Waypoints(System.Net.IPAddress ipAddress, int instructionId, byte[] ex2WaypointBytes) {
            return base.Channel.CommitEx2Waypoints(ipAddress, instructionId, ex2WaypointBytes);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> CommitEx2WaypointsAsync(System.Net.IPAddress ipAddress, int instructionId, byte[] ex2WaypointBytes) {
            return base.Channel.CommitEx2WaypointsAsync(ipAddress, instructionId, ex2WaypointBytes);
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> RequestFreeze() {
            return base.Channel.RequestFreeze();
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> RequestFreezeAsync() {
            return base.Channel.RequestFreezeAsync();
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> RequestUnfreeze() {
            return base.Channel.RequestUnfreeze();
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> RequestUnfreezeAsync() {
            return base.Channel.RequestUnfreezeAsync();
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> CreateVirtualVehicle(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.PoseData pose) {
            return base.Channel.CreateVirtualVehicle(ipAddress, pose);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> CreateVirtualVehicleAsync(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.PoseData pose) {
            return base.Channel.CreateVirtualVehicleAsync(ipAddress, pose);
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> RemoveVehicle(System.Net.IPAddress ipAddress) {
            return base.Channel.RemoveVehicle(ipAddress);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> RemoveVehicleAsync(System.Net.IPAddress ipAddress) {
            return base.Channel.RemoveVehicleAsync(ipAddress);
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> SetPose(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.PoseData pose) {
            return base.Channel.SetPose(ipAddress, pose);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> SetPoseAsync(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.PoseData pose) {
            return base.Channel.SetPoseAsync(ipAddress, pose);
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> ResetKingpin(System.Net.IPAddress ipAddress) {
            return base.Channel.ResetKingpin(ipAddress);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> ResetKingpinAsync(System.Net.IPAddress ipAddress) {
            return base.Channel.ResetKingpinAsync(ipAddress);
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> SetFleetState(FleetClients.FleetManagerServiceReference.VehicleControllerState controllerState) {
            return base.Channel.SetFleetState(controllerState);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> SetFleetStateAsync(FleetClients.FleetManagerServiceReference.VehicleControllerState controllerState) {
            return base.Channel.SetFleetStateAsync(controllerState);
        }
        
        public System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData> SetKingpinState(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.VehicleControllerState controllerState) {
            return base.Channel.SetKingpinState(ipAddress, controllerState);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, FleetClients.FleetManagerServiceReference.ServiceCallData>> SetKingpinStateAsync(System.Net.IPAddress ipAddress, FleetClients.FleetManagerServiceReference.VehicleControllerState controllerState) {
            return base.Channel.SetKingpinStateAsync(ipAddress, controllerState);
        }
    }
}
